### ISSUE TITLE
gir1.2-appindicator3-0.1 is an undocumented requirement under Ubuntu 19.10

### ISSUE THREAD

**Issue by inhumantsar** [ubuntu-mate/mate-optimus#15]
using a clean install of Ubuntu 19.10 with working nvidia 435 drivers, i ran `sudo apt install mate-optimus` as usual. the applet didn't start automatically after a reboot, so i ran the applet manually and got an error:

```
➜ mate-optimus-applet 
Traceback (most recent call last):
  File "/usr/bin/mate-optimus-applet", line 20, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available
```

googled around for the package and installed it, applet did the thing after:

```
➜ sudo apt install -y gir1.2-appindicator3
...
Setting up gir1.2-appindicator3-0.1 (12.10.1+18.04.20180322.1-0ubuntu4) ...

➜ mate-optimus-applet 
mate-optimus-applet: launched.
  - nvidia-settings and prime-select detected.
  - prime-supported: Yes
mate-optimus-applet: NVIDIA Optimus supported.
...
```

**Comment by sunweaver** [comment]
See PR #17 in addition to this.

**Comment by esa1975** [comment]
I can confirm that I had the same error on Kubuntu and was able to resolve it by installing gir1.2-appindicator3-0.1

**Comment by Akuukis** [comment]
Thanks! Confirmed on Ubuntu 20.04 - doesn't work with given error, solved by installing `sudo apt install gir1.2-appindicator3-0.1`

**Comment by ManifoldFR** [comment]
I can confirm installing the `gir1.2-appindicator3-0.1` fixes running this on Ubuntu 20.04.

**Comment by OlivierV78** [comment]
Same for me. You should add this to requirement under Ubuntu 20.04

**Comment by flexiondotorg** [comment]
This is fixed in recent releases of `mate-optimus` which now uses Ayatana Indicators and `gir1.2-ayatanaappindicator3-0.1` is a Depends in the Debian/Ubuntu packaging.

Closing this as it is distro packaging issue, which is maintained outside of this project.
